---
language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvirt-dev
  - gem update --system 2.4.8
  - gem install bundler --version $BUNDLER_VERSION
install: bundle _${BUNDLER_VERSION}_ install
script: bundle _${BUNDLER_VERSION}_ exec rspec --color --format documentation
notifications:
  email: false
rvm:
  - 2.0.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - VAGRANT_VERSION=v1.5.4 BUNDLER_VERSION=1.5.3
    - VAGRANT_VERSION=v1.6.5 BUNDLER_VERSION=1.6.9
    - VAGRANT_VERSION=v1.7.0 BUNDLER_VERSION=1.7.9
    - VAGRANT_VERSION=       BUNDLER_VERSION=1.7.9
