name: Deploy Docs Preview Cleanup
on:
  pull_request_target:
    types:
      - closed
    paths:
      - 'docs/**'
      - '.github/workflows/publish-documentation-preview.yml'
      - '.github/workflows/build-docs/**'

permissions:
  contents: write

jobs:
  remove-docs-preview:
    concurrency: publish-gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Setup
        id: setup
        run: |
          echo "pr_number=$(jq -r ".number" "$GITHUB_EVENT_PATH")" >> ${GITHUB_OUTPUT}
          echo "repo_name=$(jq -r ".repository.name" "$GITHUB_EVENT_PATH")" >> ${GITHUB_OUTPUT}

      - name: Build docs ðŸ”§
        uses: ./.github/workflows/build-docs
        with:
          target-folder: "/${{ steps.setup.outputs.repo_name }}/pr-preview/pr-${{ steps.setup.outputs.pr_number }}"

      - name: Deploy preview removal ðŸš€
        uses: rossjrw/pr-preview-action@v1
        with:
          action: remove
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
